# -*- coding: utf-8 -*-
"""Analysis_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14foAGqg478FsX5VGFTEjuXzDyJCOuwNQ
"""



import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_excel('nonu1.xlsx')
df
df.shape
df.columns
# df.info()
# df.isnull().sum()

float_col=df.select_dtypes(['float64','int64'])
for col in float_col:
    df[col]=df[col].fillna(df[col].median())
obj_col=df.select_dtypes('object')
for col in obj_col:
    df[col]=df[col].fillna("Missing")

df.isnull().sum()
df.duplicated().sum()

df['Units'].sum().mean()
df['Units'].median()

# Kaunse 5 highest Sale_amt transactions hain?
top5=df['Sale_amt'].sort_values(ascending=False).head(5)
top5

# Kaunse 5 lowest Sale_amt transactions hain?
bottom5=df['Sale_amt'].sort_values(ascending=True).head(5)
bottom5

# Total sales amount kitna hai?
kk=df['Sale_amt'].sum()
kk

# Total units sold kitne hain?
pp=df['Units'].sum()
pp
# Average sale amount per order?
h=df['Sale_amt'].mean()
h

# Average unit price?
l=df['Units'].mean()
l

# Highest single transaction kaun si hai?
highe=df['Sale_amt'].sort_values(ascending=False).head(1)
highe

# lowest single transaction kaun si hai?
low=df['Sale_amt'].sort_values(ascending=False).tail(1)
low

# Top 10 highest sales ka average kya hai?
top=df['Sale_amt'].sort_values(ascending=False).head(10).mean()
top

# bottom 10 highest sales ka average kya hai?
bot=df['Sale_amt'].sort_values(ascending=False).tail(10).mean()
bot

# Region wise total sales?
p=df.groupby('Region')['Sale_amt'].sum()
p

# Region wise total units sold?
l=df.groupby('Region')['Units'].sum()
l

# Region wise average sale amount?
k=df.groupby('Region')['Sale_amt'].mean()
k

# Sabse zyada sales kis region ne generate ki?
b=df.groupby('Region')['Sale_amt'].max()
b

# Sabse kam sales kis region ne ki?
ll=df.groupby('Region')['Sale_amt'].min()
ll
# Region wise average unit price?
k=df.groupby('Region')['Unit_price'].mean()
k

# Region wise bar chart banao (Sale_amt)
reg_wise=df.groupby('Region')['Sale_amt'].sum()
reg_wise.plot(kind='bar',title='Region wise sales',xlabel='Region',ylabel='sales')
plt.show()

# Region wise bar chart banao (Sale_amt)
reg_wise.plot(kind='pie',title='Region wise sales')
plt.show()

# Manager wise total sales?
man=df.groupby('Manager')['Sale_amt'].sum()
man

# Sabse successful manager kaun hai?
succ=df.groupby('Manager')['Sale_amt'].sum().sort_values(ascending=False).head(1)
succ

# SalesMan wise total sales?
man=df.groupby('SalesMan')['Sale_amt'].sum()
man
# Top 5 SalesMan kaun hain (sales ke hisaab se)?
top5=df.groupby('SalesMan')['Sale_amt'].sum().sort_values(ascending=False).head(5)
top5
# Kaunsa SalesMan sabse zyada units sell karta hai?
bb=df.groupby('SalesMan')['Units'].sum().sort_values(ascending=False).head(1)
bb
# Manager wise average sale amount?
o=df.groupby('Manager')['Sale_amt'].mean()
o
# SalesMan performance ka bar chart banao (top 5)
n=df.groupby('SalesMan')['Sale_amt'].sum().sort_values(ascending=False).head(5)
n.plot(kind='bar',title='SalesMan wise sales',xlabel='SalesMan',ylabel='sales')
plt.show()

# Item wise total units sold?
op=df.groupby('Item')['Units'].sum()
op
# Item wise total sales?
op=df.groupby('Item')['Sale_amt'].sum()
op
# Sabse zyada bikne wala item?
op=df.groupby('Item')['Sale_amt'].sum()
op
.

df.columns

df

