# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19lYmDimjpD03WBo25q82ldWjVTPP07qx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv('Chocolate_Sales.csv')
# columns:::['Sales Person', 'Country', 'Product', 'Date', 'Amount','Boxes Shipped']


# 1. Dataset Overview
# .head()
# .tail()
# .shape
# .columns
# .info()
# .describe()
df.shape
df.columns
df.info()
df.describe()

# 2. Missing Values
# .isnull().sum()
df.isnull().sum()

# 3. Duplicate Records
# .duplicated().sum()
df.duplicated().sum()

# Basic Sales Analysis
df['Amount'].sum()
df['Boxes Shipped'].sum()
df['Sales Person']
df['Product']

df.groupby('Country')['Product'].sum().sort_values(ascending=False)
df.groupby('Sales Person')['Amount'].sum().sort_values(ascending=False)
df['Amount']=df['Amount'].replace("[$,]","",regex=True).astype(float)
df['Amount']
#product wise sales
df.groupby('Product')['Amount'].sum().sort_values(ascending=False)
#country wise sales
df.groupby('Country')['Amount'].sum().sort_values(ascending=False)
# which country top profit
df.groupby('Country')['Amount'].sum().sort_values(ascending=False).head(1)
#Product wise Profit
df.groupby('Product')['Amount'].sum().sort_values(ascending=False)
# Product wise Profit top one
df.groupby('Product')['Amount'].sum().sort_values(ascending=False).head(1)

# Visualization (Matplotlib)
top_product=df.groupby('Product')['Amount'].sum().sort_values(ascending=False).head(5)
top_product.plot(kind='bar')
plt.title("top 5 products")

#country sales pie chart
country_sales=df.groupby('Country')['Amount'].sum().sort_values(ascending=False)
country_sales.plot(kind='pie')
plt.title("country sales")



