# -*- coding: utf-8 -*-
"""Business_Analysis_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I23oDxbFKYI-OLAjjLSzDva2qOOU0Bg4
"""

import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd

data = {
    'Date': [
        '2023-01-10','2023-02-15','2023-03-20','2023-04-25',
        '2023-05-10','2023-06-15','2023-07-20','2023-08-25',
        '2023-09-10','2023-10-15','2023-11-20','2023-12-25'
    ],
    'Product': [
        'A','B','A','C','B','A','C','A','B','C','A','B'
    ],
    'Region': [
        'Karachi','Lahore','Karachi','Islamabad','Lahore','Karachi',
        'Islamabad','Karachi','Lahore','Islamabad','Karachi','Lahore'
    ],
    'Sales': [
        500,600,550,400,450,300,350,280,260,200,180,150
    ],
    'Customer_Rating': [
        5,4,4,3,3,2,2,1,2,1,1,1
    ]
}

df = pd.DataFrame(data)
print(df)

df = pd.DataFrame(data)


df['Date'] = pd.to_datetime(df['Date'])


df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month


monthly_sales = df.groupby('Month')['Sales'].sum()

plt.figure()
plt.plot(monthly_sales.index, monthly_sales.values, marker='o')
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.show()


product_sales = df.groupby('Product')['Sales'].sum()

plt.figure()
plt.bar(product_sales.index, product_sales.values)
plt.title("Sales by Product")
plt.show()

best_product = product_sales.sort_values(ascending=False).head(1)
worst_product = product_sales.sort_values(ascending=True).head(1)

print("Best Product:\n", best_product)
print("Worst Product:\n", worst_product)


region_sales = df.groupby('Region')['Sales'].sum()

plt.figure()
plt.bar(region_sales.index, region_sales.values)
plt.title("Sales by Region")
plt.show()

best_region = region_sales.sort_values(ascending=False).head(1)
worst_region = region_sales.sort_values().head(1)

print("Best Region:\n", best_region)
print("Worst Region:\n", worst_region)


ratings = df.groupby('Product')['Customer_Rating'].mean()

plt.figure()
plt.bar(ratings.index, ratings.values)
plt.title("Customer Ratings by Product")
plt.show()

print("Ratings:\n", ratings)


#CONCLUSION INSIGHT:---
'''
 “Sales decline ka main reason Product C ki poor performance hai,
  jiska customer rating bhi low hai.
  Iska impact Islamabad region me zyada hai jahan overall sales lowest hain.
  Company ko Product C ki quality improve karni chahiye
  aur Islamabad region me targeted marketing karni chahiye.”
'''









