# -*- coding: utf-8 -*-
"""Dashboard_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vNj6coTo7t7djn89HUBWGfgN1PwDH_ex
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

data = {
    'Date': [
        '2023-01-10','2023-02-15','2023-03-20','2023-04-25',
        '2023-05-10','2023-06-15','2023-07-20','2023-08-25',
        '2023-09-10','2023-10-15','2023-11-20','2023-12-25'
    ],
    'Product': [
        'A','B','A','C','B','A','C','A','B','C','A','B'
    ],
    'Region': [
        'Karachi','Lahore','Karachi','Islamabad','Lahore','Karachi',
        'Islamabad','Karachi','Lahore','Islamabad','Karachi','Lahore'
    ],
    'Sales': [
        500,600,550,400,450,300,350,280,260,200,180,150
    ],
    'Customer_Rating': [
        5,4,4,3,3,2,2,1,2,1,1,1
    ]
}

df = pd.DataFrame(data)
print(df)
sns.set(style="whitegrid")
df['Date']=pd.to_datetime(df['Date'])
df['Month']=df['Date'].dt.month
df['Year']=df['Date'].dt.year
df['Quarter']=df['Date'].dt.quarter
df
plt.figure(figsize=(15,10))
plt.suptitle("Sales Dashboard Analysis", fontsize=16)

# 📈 1. Monthly Sales Trend
plt.subplot(2,2,1)
monthly_sales=df.groupby('Month')['Sales'].sum()
plt.plot(monthly_sales.index,monthly_sales.values,marker='o',linestyle='-')
plt.title('Monthly Sales Trend')
plt.xlabel('Month')
plt.ylabel('Sales')

# 🏆 2. Product Sales
plt.subplot(2,2,2)
prod_sales=df.groupby('Product')['Sales'].sum()
plt.bar(prod_sales.index,prod_sales.values)
plt.title("Product Sales")
plt.xlabel('Product')
plt.ylabel('Sales')

# 🌍 3. Region Sales
plt.subplot(2,2,3)
reg_sales=df.groupby('Region')['Sales'].sum()
plt.pie(reg_sales.values,labels=reg_sales.index,autopct='%1.1f%%')

# ⭐ 4. Customer Ratings
plt.subplot(2,2,4)
cust_rating=df.groupby('Product')['Customer_Rating'].sum()
plt.bar(cust_rating.index,cust_rating.values)

plt.xlabel('Product')
plt.ylabel('Customer Rating')

plt.tight_layout()
plt.show()

