# -*- coding: utf-8 -*-
"""Date_time.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TYw7FVsEhz7r8JXJtfw1txvCkWcQ4RMX
"""

import pandas as pd
data = {
    "date": [
        "2024-01-05", "2024-01-15", "2024-02-10",
        "2024-02-20", "2024-03-05", "2024-03-25",
        "2024-04-10", "2024-04-18", "2024-05-02",
        "2024-05-22", "2024-06-12", "2024-06-28"
    ],
    "sales": [100, 150, 200, 180, 220, 250, 300, 280, 260, 290, 310, 330]
}
df=pd.DataFrame(data)
df

# df.dtypes
df['date']=pd.to_datetime(df['date'])
df.dtypes

df['year']=df['date'].dt.year
df['month']=df['date'].dt.month

monthly_sales=df.groupby('year')['sales'].sum().sort_values(ascending=False)
monthly_sales

monthly_sales=df.groupby('month')['sales'].sum().sort_values(ascending=False)
monthly_sales

lk = {
    "date": [
        "2024-01-01", "2024-01-05", "2024-01-20",
        "2024-02-02", "2024-02-18",
        "2024-03-10", "2024-03-25",
        "2024-04-15"
    ],
    "sales": [100, 150, 200, 250, 180, 300, 220, 400]
}
df = pd.DataFrame(lk)
print(df)

df["date"] = pd.to_datetime(df["date"])
df.set_index("date", inplace=True)
print(df)

monthly=df.resample("M").sum()
monthly

weekly=df.resample("W").sum()
weekly

yearly=df.resample("Y").sum()
yearly

quarterly = df.resample("Q").sum()
print(quarterly)

monthly_avg=df.resample("M").mean()
monthly

weekly_maxsales=df.resample("W").max().tail(1)
weekly_maxsales

