# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rxx0RfWvAr4anehVYc_7szN13wuZQG0X
"""

import matplotlib.pyplot as plt

x=[1,2,3,4,5]
y=[10,20,30,40,50]
plt.plot(x,y)
plt.show()

from matplotlib.lines import lineStyles
plt.figure(figsize=(4,4))
x=["A","B","C"]
y=[10,50,20]
plt.plot(x,y,color='red',marker='o',linestyle='dashed',linewidth=2,markersize=4,label="huzaifa")
plt.title("My Customize Chart")
plt.xlabel("product")
plt.ylabel("sales")
plt.legend()

#multiple lines and legends
a=[1,2,3,4]
b1=[10,60,30,500]
b2=[50,60,40,90]
plt.plot(a,b1,label="sales2024",color="red")
plt.plot(a,b2,label="sales2025",color="blue")
plt.title("My Customize Chart")
plt.legend()
plt.xlabel("product")
plt.ylabel("sales")

x=[1,2,3]
y=[20,40,10]
plt.bar(x,y,color="red")
plt.show()

import random
data=[random.randint(1,100) for _ in range(100)]
plt.hist(data,bins=20)
plt.title("histogram")

x=["a","b","c","d"]
y=[20,40,30,60]
plt.pie(y,labels=x,autopct='%1.1f%%')
plt.title("pie chart")

plt.figure(figsize=(5,5))
x=["a","b","c","d","e","f"]
y=[20,40,30,60,25,35]
plt.scatter(x,y)
plt.title("scatter chart")

category=["a","b","c","d","e","f"]
sales=[10,30,50,20,80,55]
y1=[1,2,3,4]
y2=[10,20,30,40]
plt.figure(figsize=(5,4))
plt.subplot(1,2,1)
plt.bar(category,sales)
plt.subplot(1,2,2)
plt.scatter(y1,y2)
plt.show()

#matplotlib with pandas
import pandas as pd
data={
    'month':["jan","feb","mar","apr","may"],
    'sales':[100,200,300,400,500]
}
df=pd.DataFrame(data)
plt.bar(df['month'],df['sales'])
plt.title("bie chart by pandas")
plt.xlabel("month")
plt.ylabel("sales")
plt.savefig("mychart.png")

import pandas as pd
import matplotlib.pyplot as plt
data={
    "purchase amount":[1000,2000,3000,4000],
    "product":["mango","apple","papaya","kiwi"]

}
df=pd.DataFrame(data)
plt.figure(figsize=(4,4))
plt.hist(df["purchase amount"],bins=12)
plt.title("histogram")
plt.show()
plt.figure(figsize=(4,4))
plt.pie(df['purchase amount'],labels=df["product"])
plt.title("pie chart")
plt.show()



import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

days=np.arange(1,11)
sales=np.random.randint(100,500,10)
df=pd.DataFrame({
    "days":days,
    "sales":sales
})
plt.figure(figsize=(4,4))
plt.plot(df['days'],df['sales'])
plt.title("line chart")
plt.xlabel("days")
plt.ylabel("sales")
plt.show()

x=[1,2,3,4,5]
y=[10,20,30,40,50]
plt.figure(figsize=(4,4))
plt.plot(x,y,color='red',label="huzaifa",marker='o',markeredgecolor)