# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eJWuHIGG29-kIblOYTH47tqt9TY4GdwP
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
df=pd.read_csv("mobile.csv")
df
df.isnull().sum()
df.shape
df.dtypes
q1=df['Daily_Phone_Hours'].quantile(0.25)
q3=df['Daily_Phone_Hours'].quantile(0.75)
iqr=q3-q1
iqr
lf=q1-1.5*iqr
uf=q3+1.5*iqr
lf
uf
outliers=df[(df['Daily_Phone_Hours']<lf) | (df['Daily_Phone_Hours']>uf)]
outliers
sns.boxplot(x='Gender',y='Daily_Phone_Hours',data=df)

sns.scatterplot(x='Age',y='Daily_Phone_Hours',data=df)

sns.histplot(df['Daily_Phone_Hours'],bins=20,kde=True)
plt.xlabel('Daily_Phone_Hours')
plt.ylabel('Frequency')

df['Age_Group']=pd.cut(df['Age'],bins=[10,20,30,40,50,60])

k=df.groupby('Age_Group')['Daily_Phone_Hours'].mean()
k

df['usage_segment']=pd.qcut(df['Daily_Phone_Hours'],q=[0,0.5,1.0],labels=["A","B"])
df['usage_segment']

Df['test_deciles']=pd.qcut(df['Daily_Phone_Hours'],q=10,labels=['a','b','c','d','e','f','g','h','i','j'])
df.test_deciles

sns.boxplot(x='usage_segment',y='Sleep_Hours',data=df)
sns.pairplot(df[['Age','Daily_Phone_Hours','Sleep_Hours','Caffeine_Intake_Cups']])

