# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CRxr0yEpuhaSOcVkfu4v03cp3yEV1rao
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv("hk1.csv")
df
df.isnull().sum()
df.duplicated().sum()
df.dtypes
df['Runtime']=df['Runtime'].str.replace("min","",regex=False)
df['Runtime']=pd.to_numeric(df['Runtime'])
df.dtypes
df['Released_Year']=pd.to_numeric(df['Released_Year'],errors='coerce')
df.dtypes
df
df['Gross']=pd.to_numeric(df['Gross'],errors='coerce')
df.dtypes
df['Meta_score']=df['Meta_score'].fillna(df['Meta_score'].median())
df.isnull().sum()
df['Gross']=df['Gross'].fillna(df['Gross'].median())
df.isnull().sum()
df['Released_Year']=df['Released_Year'].fillna(df['Released_Year'].median())
df.isnull().sum()
df['Certificate']=df['Certificate'].fillna(df['Certificate'].mode()[0])
df.isnull().sum()

plt.figure(figsize=(5,5))
plt.hist(df['Runtime'],bins=20)
plt.title("runtime distribution")

revenue=df.groupby('Genre')['Gross'].sum()
plt.figure(figsize=(5,5))
plt.plot(revenue)
plt.title("revenue by genre")

dir_performance=df.groupby('Director')['Gross'].sum()
plt.figure(figsize=(5,5))
plt.plot(dir_performance)


k=df.groupby('Released_Year')['Gross'].sum()
plt.figure(figsize=(10,5))
plt.plot(k)
plt.title("revenue by year")

plt.plot(df.groupby('Series_Title')['Gross'].sum())
plt.title("revenue by movie")

plt.figure(figsize=(5,5))
plt.hist(df['Gross'],bins=30)
plt.title("gross distribution")

plt.figure(figsize=(5,5))
plt.hist(df['IMDB_Rating'],bins=30)
plt.title("Rating")

l=df.groupby('Series_Title')['Gross'].max().sort_values().head(10)
print(l)

plt.figure(figsize=(5,5))
plt.scatter(df['Gross'],df['IMDB_Rating'])
plt.title("gross vs rating")

plt.figure(figsize=(5,5))
plt.scatter(df['IMDB_Rating'],df['No_of_Votes'])
plt.title("rating vs votes")



