# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fTVS21D1QnF-vF4bKABVs8jNEetHNhqf
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv("hk1.csv")

# ['Series_Title', 'Released_Year', 'Certificate', 'Runtime', 'Genre',
#        'IMDB_Rating', 'Meta_score', 'Director', 'Star1', 'No_of_Votes',
#        'Gross']

# 🟢 Section 1 – Basic Exploration (EDA)----
# Total kitni movies hain dataset me?
o=df['Series_Title'].count()
#
# Average IMDB rating kya hai?
df[['IMDB_Rating']].mean()
# Maximum aur minimum rating wali movie kaun si hai?
l=df.groupby('Series_Title')['IMDB_Rating'].min().sort_values().head(1)
print(l)
m=df.groupby('Series_Title')['IMDB_Rating'].max().tail(1)
print(m)

# Sabse zyada votes kis movie ke hain?
j=df.groupby('Series_Title')['No_of_Votes'].max().sort_values().tail(1)
j
# Kitni movies ka Meta_score missing hai?
df['Meta_score'].isnull().sum()
# Top 10 highest rated movies kaun si hain?
high=df.groupby('Series_Title')['IMDB_Rating'].max().sort_values().tail(10)
high
#
# Lowest 10 rated movies kaun si hain?
low=df.groupby('Series_Title')['IMDB_Rating'].min().sort_values().head(10)
low
# Average Gross kitna hai?
df['Gross'].mean()

# Kitni movies ka Gross missing hai?
df['Gross'].isnull().sum()
# Sabse zyada repeat hone wala Genre kaunsa hai?
p=df['Genre'].mode()
p
#🟢Section 3 – Votes Analysis--------

# Average votes kitne hain?
jj=df['No_of_Votes'].mean()
jj
# Top 10 most voted movies kaun si hain?
n=df.groupby('Series_Title')['No_of_Votes'].max().sort_values().tail(10)
n
# Lowest voted movies kaun si hain?
p=df.groupby('Series_Title')['No_of_Votes'].max().sort_values().head(10)
p
# Kya high rating movies ke votes bhi zyada hote hain?

# Votes ka distribution histogram me dikhao.

plt.figure(figsize=(10,5))
plt.hist(df['No_of_Votes'],bins=20)
plt.show()

# Section 4 – Rating vs Votes (IMPORTANT 🔥)-----

# IMDB_Rating aur No_of_Votes ka correlation nikalo.
pp=df['IMDB_Rating'].corr(df['No_of_Votes'])
print(f"correlation between rating and votes {pp}")
# Scatter plot banao (Votes vs Rating).

plt.figure(figsize=(10,5))
plt.scatter(df['No_of_Votes'],df['IMDB_Rating'])
plt.show()

# High rating (8.5+) movies ka average votes nikalo.
high_rating=df[df['IMDB_Rating']>8.5]
high_vote=high_rating['No_of_Votes'].mean()
print(f"average votes of high rating movies {high_vote}")
# Low rating (<7) movies ka average votes nikalo.
low_rating=df[df['IMDB_Rating']<7]
low_vote=high_rating['No_of_Votes'].mean()
print(f"average votes of high rating movies {low_vote}")
# Kya 1 million se zyada votes wali movies ka rating average alag hai?

# 🟢 Section 5 – Year Analysis------


# Kis decade me sabse zyada movies release hui?

# Har year ka average rating nikalo.

# Har year ka total votes nikalo.

# Line chart banao Year vs Average Rating.

# Line chart banao Year vs Total Votes.

# 🟢 Section 6 – Genre & Director Analysis----

# Kis director ki movies ka average rating sabse zyada hai?
h=df.groupby('Director')['IMDB_Rating'].max().sort_values().tail(1)
h

# Har genre ka average rating nikalo.
h=df.groupby('Genre')['IMDB_Rating'].max().sort_values()
h

# Har genre ka total votes nikalo.
h=df.groupby('Genre')['No_of_Votes'].max().sort_values()
h
# Top 5 highest grossing genres kaun se hain?
k=df.groupby('Genre')['Gross'].max().sort_values().tail(5)
k

# Director vs total votes ka bar chart banao (Top 10)

p=df.groupby('Director')['No_of_Votes'].max().sort_values().tail(10)
plt.bar(p.index,p.values)
plt.show()

df.columns

