# -*- coding: utf-8 -*-
"""MTID_VCTRZN_TMSRS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mEsqJ0-V4fX4i_KtEJGmCpfMPMfUUHvE
"""

import pandas as pd
#multi indexing
data = {
    'City': ['Karachi', 'Karachi', 'Lahore', 'Lahore'],
    'Product': ['A', 'B', 'A', 'B'],
    'Sales': [100, 200, 150, 300]
}
df=pd.DataFrame(data)
print(df)
multi_index=df.set_index(['City','Product'])
print(multi_index)

#vectorization
# df['Bonus'] = []

# for i in df['Sales']:
#     df['Bonus'].append(i * 0.1)

# df['Bonus'] = df['Sales'] * 0.1

#resample
import pandas as pd

data = {
    'Date': pd.date_range(start='2024-01-01', periods=6, freq='D'),
    'Sales': [100, 200, 150, 300, 250, 400]
}

df = pd.DataFrame(data)
df.set_index('Date', inplace=True)
monthly = df.resample('M').sum()
print(monthly)
weekly=df.resample('W').mean()
print(weekly)

