# -*- coding: utf-8 -*-
"""numpy_practice2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hw_C745PscdfcYaPgiLh_W17H022LvQ7
"""

import numpy as np
arr1=np.arange(20).reshape(4,5)
arr1
arr2=np.arange(20,40).reshape(4,5)
arr2

#Arrays with same shape and dimensions can be computed arithmetically
arr1+arr2

arr1*arr2

arr2-10

ar1 = np.array([1,2,3,4,5,6,7,8,9,0])
ar1[3]
ar1[-3]
ar1[3:6]

arr = np.array(range(20))
arr
arr[arr%2!=0]

arr[(arr>5)&(arr<15)]

