# -*- coding: utf-8 -*-
"""numpy_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FbZUzmzHzktSF6tkngiiUGW8KfDfSpzY
"""

list_a=list(range(1,100))
print(list_a)

cover=[]
for i in list_a:
  cover.append(i*i)
print(cover)

print([a**2 for a in list_a])

import numpy as np
arr1=np.array(list_a)
arr1
arr1**2
arr2=np.array([1,2,3,4])
arr2*2

#Methods to create an array
#using python list
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr1

#using numpy arange
ar=np.arange(10)
print(ar)
ar1=np.random.randn(1,10)
ar1
ar2=np.random.rand(1,10)
print(ar2)

arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d
arr2d.ndim
arr2d.size
arr2d.shape

#array of 5 rows 4 columns
arr2dd=np.random.rand(5,4)
arr2dd

#array 5 rows 4 columns 3 set
arr2ddd=np.random.rand(3,5,4)
arr2ddd

arr3d1=np.arange(64)
arr3d1.reshape(4,4,4)

zeros=np.zeros(6)
zeros

zeros.dtype

zeross=np.zeros((6,5))
zeross

ones=np.ones(6)
ones

ones.dtype

onesss=np.ones((6,5))
onesss

identity=np.eye(4)
identity

np.ones((4,4))*15

np.full((4,4),10)

