# -*- coding: utf-8 -*-
"""Outliers_Detect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tHDzDf9MzpWDqgpFvH4xeaAgWF1V7eA0
"""

import pandas as pd
data=[18,19,20,21,22,23,100]
df=pd.DataFrame(data,columns=['age'])
Q1=df['age'].quantile(0.25)
Q3=df['age'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-1.5*IQR
upper=Q3+1.5*IQR

outliers=df[(df['age']<lower)|(df['age']>upper)]
print(outliers)

