# -*- coding: utf-8 -*-
"""Pandas_Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cmA4YqzTcnNJUDpgfPdXbP8HqAg-0Fk5
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

s1=pd.Series([1,2,3,4,5,6])
s1
s1.index
s1.values
s1.dtypes
s2=pd.Series([2,4,6,8,10],index=['a','b','c','d','e'])
s2
s2[4]
s2[1:4]
s2>8
s2[s2>6]
s2['b']
s2.size
s2.shape

data={"rollno":[1,2,3],
      "name":['ali',"ahmed","sara"],
      "maths":[78,85,98],
      "urdu":[65,75,80]}
data
df=pd.DataFrame(data)
df
df.head(2)
df.tail(2)

df=pd.read_excel('emp_data.xlsx')
df
df.columns

# 'Serial', 'Emp_ID', 'Designation', 'Department', 'Age', 'Salary'
type(df)
df['Department']
df[['Department','Designation','Age']]
df['Age']
df

df['Bonus']=50000
df.rename(columns={'Designation':'New_Id'},inplace=True)
df.rename(columns={'Department':'Designation'},inplace=True)
df.rename(columns={'Age':'Department'},inplace=True)
df.rename(columns={'Salary':'Age'},inplace=True)
df.rename(columns={'Unnamed: 6':'Salary'},inplace=True)
df.drop('Emp_ID',axis=1,inplace=True)
df.drop('Serial',axis=1,inplace=True)
df

df['New_Bonus']=[50000 if((des=='Manager')or(des=='Engineer'))else 40000
                 if des=='Accountant' else 30000
                 if des=='Officer'else 20000 for des in df['Designation']]
df['N_Bonus']=[50000 if ((des=='Manager') or (des=='Engineer')) else 40000 if des=='Acountant' else 30000 if
               des=='Officer' else 20000 for des in df.Designation]
df
df['Bonus_1'] = [50000 if ((des=='Manager') or (des=='Engineer'))
               else 40000 if des=='Accountant'
               else 30000 if des=='Officer'
               else 20000 for des in df['Designation']]
bonus_map = {
    'manager': 50000,
    'engineer': 50000,
    'accountant': 40000,
    'officer': 30000
}

df['Bonus2'] = df['Designation'].str.lower().str.strip().map(bonus_map).fillna(20000)
df
# df['Bonus3'] = [sal*0.5 if sal>=200000
#                else sal*0.25 if sal>=150000
#                else sal*0.15 if sal>=75000
#                else sal*0.10
#                for sal in df.Salary]
df['Bonus_5']=df.Salary.apply(lambda sal:sal*0.5 if sal>=200000 else sal*0.25 if sal>=10000 else sal*0.15 if sal>=50000 else sal*10 )