# -*- coding: utf-8 -*-
"""Patterns_logic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ic2Ptc0d6oH-clyjy5w999HlR5C6j50H
"""

#square

for i in range(5):
  for j in range(5):
    print("*",end=' ')
  print()

#hollow square

n=int(input("enter any number"))
for i in range(n):
  for j in range(n):
    if i==0 or i==n-1 or j==0 or j==n-1:
      print("*" ,end=' ')
    else:
      print(" ",end=' ')
  print()

#right angle
for i in range(5):
  print("*"*i)

#inverted right angle
for i in range(5,0,-1):
  print("*"*i)

#left inverted right triangle
for i in range(5,0,-1):
  for j in range(5):
    if j>=5-i:
      print("*",end=' ')
    else:
      print(" ",end=' ')
  print()

#right left triangle
for i in range(5):
  for j in range(5):
    if j>=5-i:
      print("*",end=' ')
    else:
      print(" ",end=' ')
  print()

#diamond
for i in range(1,5):
  for j in range(1,8):
    if j>=5-i and j<=3+i:
      print("*",end=' ')
    else:
      print(' ',end=' ')
  print()
for i in range(3,0,-1):
  for j in range(1,8):
    if j>=5-i and j<=3+i:
      print("*",end=' ')
    else:
      print(' ',end=' ')
  print()

for i in range(1,5):
  for j in range(1,8):
    if j==5-i or j==3+i:
      print("*",end=' ')
    else:
      print(' ',end=' ')
  print()
for i in range(3,0,-1):
  for j in range(1,8):
    if j==5-i or j==3+i:
      print("*",end=' ')
    else:
      print(' ',end=' ')
  print()

#pyramid


n = 4

for i in range(1, n+1):
    print(" " * (n-i) + "*" * (2*i-1))

# n=4
# for i in range(1,5):
#   for j in range(n-i):
#     print(" ", end='')
#   for j in range(2*i-1):
#     print("*", end='')
#   print()

#hollow pyramid
n = 4

for i in range(1,n+1):
  for j in range(1,n*2):
    if j == n-i+1 or j == n+i-1 or i == n:
      print('*',end='')
    else:
      print(' ',end='')
  print()

