# -*- coding: utf-8 -*-
"""pivot_table.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M7U5oZa7LplmM0JzMwVwpIcv4GN2QIde
"""

import pandas as pd
data = {
    'Name': ['Ali', 'Ahmed', 'Ali', 'Ahmed'],
    'City': ['Karachi', 'Lahore', 'Karachi', 'Lahore'],
    'Sales': [100, 200, 150, 300]
}
df=pd.DataFrame(data)
pivot=df.pivot_table(values='Sales',columns='City',aggfunc='sum')
print(pivot)

