# -*- coding: utf-8 -*-
"""Titanic_Eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xnJr6gC-7_NB1GP5Xma6OkJX0whLZpwQ
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('titanic.csv')

# 'PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
#        'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'

df.head()

df.shape

df.columns

df.tail()

df.info()

df.dtypes

df.duplicated()

df.duplicated().sum()

df.isnull().sum()

df.drop('Cabin',axis=1)
df.columns

df.drop('Cabin',axis=1,inplace=True)
df.columns

df['Embarked']=df['Embarked'].fillna(df['Embarked'].mode()[0])
df.isnull().sum()

df['Age']=df['Age'].fillna(df['Age'].median())
df.isnull().sum()

sns.countplot(x='Survived',hue='Sex',data=df)
plt.title("Survived Vs Non Survived")

plt.ylabel("Count")
plt.xticks([0,1],['Not Survived','Survived'])

sns.countplot(x='Pclass',hue='Survived',data=df)
plt.title("Survived Vs Non Survived")
plt.xticks([0,1,2],['1stclass','2ndclass','3rdclass'])
plt.ylabel("count")

sns.histplot(df['Age'],bins=20,kde=True)
plt.title("Age Distribution")
plt.xlabel("Age")

df["FamilySize"] = df['Parch'] + df['SibSp'] + 1
df[['Name','FamilySize']]
df['FamilySize'].sum()
df['FamilySize'].max()
df['FamilySize'].value_counts().sort_index()

import numpy as np
df['IsAlone']=np.where(df['FamilySize']==1,1,0)
df.head(2)

sns.countplot(x='Survived',hue='IsAlone',data=df)
plt.title("Solo:-Survived Vs Non Survived")
plt.xticks([0,1],['Not Alone','Alone'])
plt.ylabel("count")

sns.countplott()

sns.countplot(x='FamilySize',hue='Survived',data=df)
plt.title('Survival Count by Family Size')

plt.ylabel('Count')
plt.xticks(rotation=0)
plt.legend(title='Survived', labels=['No', 'Yes'])
plt.show()

df.groupby('Sex')['Survived'].sum()
df.groupby('Pclass')['Survived'].sum()
df.groupby('Embarked')['Survived'].sum().sort_values()

df['Age_Group']=pd.cut(df['Age'],bins=[0,14,45,65],labels=['chilren','Teens','Adults'])
df.head(1)

sns.countplot(x='Age_Group',hue='Survived',data =df)
plt.legend(title="Survived",labels=['No','Yes'])
plt.title("Survival Count by Age Group")
df.drop('PassengerId',axis=1)

df[['Survived']].sum()

plt.figure(figsize=(15,12))

sns.countplot(x='Fare',hue='Survived',data=df)
plt.title("money vs survival")

