# -*- coding: utf-8 -*-
"""Trends.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GBRBKKMJroGDlUMnNBe8NS45phwMOhhw
"""

import pandas as pd
import matplotlib.pyplot as plt

data=[100,200,300,400]
months=['jan','feb','march','april']

plt.plot(months,data)
plt.title("sale trends")

